force-app/main/default/objects/SeasonsConfiguration__c/SeasonsConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Seasons Configuration</label>
</CustomObject>

force-app/main/default/objects/SeasonsConfiguration__c/fields/Cadence__c.field-meta.xml
<CustomField>
    <fullName>Cadence__c</fullName>
    <label>Cadence</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SeasonsConfiguration__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SeasonsConfiguration__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Start date of the first season with selected cadence</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SeasonsCardController.cls
public with sharing class SeasonsCardController {
    @AuraEnabled(cacheable=true)
    public static DataWrappers.SeasonConfig getSeasonsConfig() {
        DataWrappers.SeasonConfig seassonsConfig = new DataWrappers.SeasonConfig();

        SeasonsConfiguration__c seasonsCustomSetting = SeasonsConfiguration__c.getOrgDefaults();
        if (seasonsCustomSetting.Id != null) {
            seassonsConfig.id = seasonsCustomSetting.Id;
            seassonsConfig.isActive = seasonsCustomSetting.IsActive__c;
            seassonsConfig.cadence = seasonsCustomSetting.Cadence__c;
            seassonsConfig.startDate = seasonsCustomSetting.StartDate__c;
        } else {
            seassonsConfig.isActive = false;
            seassonsConfig.cadence = 'month';
            Date nextMonth = Date.today().addMonths(1);
            seassonsConfig.startDate = Date.newInstance(nextMonth.year(), nextMonth.month(), 1);
        }

        return seassonsConfig;
    }
}